### ISSUE TITLE
Error when trying to launch GUI

### ISSUE THREAD

**Issue by egeissen** [MetaSys-LISBP/PhysioFit#17]
Dear all, after installing PhysioFit I get the following error when trying to launch the PhysioFit GUI. I am on Windows using Anaconda Navigator 2.3.2
Any help would be appreciated. 
Best,
Eva
![physiofit](https://user-images.githubusercontent.com/118896710/203532107-c7222b4d-d2b1-4777-8d14-eff1285151fc.PNG)

**Comment by llegregam** [comment]
Hello, thank you for bringing this issue up. The problem comes from the new system for type hinting, which is only available for python 3.10. An upgrade of python should fix the error. 
In the meantime I will create an update of the software that will fix the issue for earlier versions of python. Expect it to be released sometime today.
Regards

**Comment by llegregam** [comment]
An update has been released with a fix for the reported bug. Please update with the `pip install --upgrade physiofit` command.
Thank you for your contribution.

**Comment by egeissen** [comment]
Perfect! Thank you so much for fixing this so quickly.
